# syntax=docker/dockerfile:1

# Production Dockerfile (Module 25 — Production Infrastructure).
#
# Multi-stage build producing a minimal runtime image from Next.js's
# `output: "standalone"` build (see next.config.ts) — the final image
# ships only the pruned `node_modules` subset Next.js determined are
# actually required at runtime, the compiled `.next` server output, and
# static assets, not the full source tree, devDependencies, or build
# toolchain.
#
# Prisma migrations are deliberately NOT run automatically by this image
# (no `prisma migrate deploy` in the entrypoint) — see
# docs/MODULE_25_PRODUCTION_INFRASTRUCTURE.md, "Database migration
# safety", for why migrations are a separate, explicit deployment step
# rather than something that runs implicitly whenever a container starts
# (multiple replicas starting concurrently must never race to apply the
# same migration).

ARG NODE_VERSION=20-alpine

# ---- deps: install dependencies (full, incl. devDependencies for the build) ----
FROM node:${NODE_VERSION} AS deps
WORKDIR /app
COPY package.json package-lock.json ./
COPY prisma ./prisma
RUN npm ci

# ---- builder: compile the Next.js production build ----
FROM node:${NODE_VERSION} AS builder
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY . .
ENV NEXT_TELEMETRY_DISABLED=1

# Build-time placeholders only.
# Real production secrets are injected at container runtime via
# docker-compose.prod.yml -> env_file: .env
ENV NEXT_PUBLIC_APP_URL=http://localhost:3000
ENV DATABASE_URL=postgresql://postgres:postgres@postgres:5432/maestroya?schema=public
ENV AUTH_SECRET=build-only-placeholder-auth-secret-32-characters
ENV AUTH_URL=http://localhost:3000
ENV AUTH_TRUST_HOST=true
ENV STRIPE_SECRET_KEY=sk_test_build_placeholder
ENV STRIPE_PUBLISHABLE_KEY=pk_test_build_placeholder
ENV STRIPE_WEBHOOK_SECRET=whsec_build_placeholder
ENV CLOUDINARY_CLOUD_NAME=build-placeholder
ENV CLOUDINARY_API_KEY=build-placeholder
ENV CLOUDINARY_API_SECRET=build-placeholder

RUN npx prisma generate
RUN npm run build

# ---- runner: minimal production image ----
FROM node:${NODE_VERSION} AS runner
WORKDIR /app

ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1
ENV PORT=3000
ENV HOSTNAME=0.0.0.0

# Non-root execution — never run the production server as root.
RUN addgroup --system --gid 1001 nodejs \
  && adduser --system --uid 1001 nextjs

COPY --from=builder /app/public ./public
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static
COPY --from=builder /app/prisma ./prisma

USER nextjs

EXPOSE 3000

# Container-level liveness check hitting the app's own liveness endpoint
# (see src/app/api/health/route.ts) — deliberately the liveness check,
# not readiness, for the same reason a Kubernetes/orchestrator liveness
# probe should point at it: a transient DB issue must not cause Docker to
# restart a perfectly healthy process.
HEALTHCHECK --interval=30s --timeout=5s --start-period=15s --retries=3 \
  CMD node -e "fetch('http://localhost:'+process.env.PORT+'/api/health').then(r=>{if(!r.ok)process.exit(1)}).catch(()=>process.exit(1))"

# `server.js` is generated by Next's standalone output — it starts its
# own minimal HTTP server (no need for `next start`/the full CLI here).
CMD ["node", "server.js"]
